# Dataset config
TRAIN_SRC_PATH = ""
TRAIN_TGT_PATH = ""
DEV_SRC_PATH = ""
DEV_TGT_PATH = ""
TEST_SRC_PATH = ""
TEST_TGT_PATH = ""

# Tokenizer config
VOCAB_SIZE = 16000
SPM_MODEL_PATH = "spm.model"
PAD_ID = 0
UNK_ID = 1
BOS_ID = 2
EOS_ID = 3

# Training config
SEED = None
BATCH_SIZE = 32
NUM_EPOCHS = 10
LAST_CHECKPOINT_PATH = "last_checkpoint.pt"
BEST_MODEL_PATH = "best_model.pt"
BASE_MODEL_PATH = "base_model.pt"
LEARNING_RATE = 3e-4
DROPOUT_RATE = 0.25
RESUME_TRAINING = False

# Model Config
MODEL_DIM = 256
HEAD_DIM = 64
SSM_STATE_DIM = 64
SSM_CONV_KERNEL_SIZE = 4
SSM_NUM_GROUPS = 1
SSM_CHUNK_SIZE = 256
NUM_LAYERS = 4

# Infer config
ATTN_GATE_THRESHOLDS = [0.0, 0.0, 0.0, 0.0]
MAX_NEW_TOKENS = 250
CACHE_UPDATE_INTERVAL = 100
PREDS_PATH = "preds.csv"